##===- projects/float-range/lib/Makefile--------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=FloatRange

include $(LEVEL)/Makefile.common
